// Code generated by "stringer -type CaseType"; DO NOT EDIT.

package mapper

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Pascal-1]
	_ = x[Camel-2]
	_ = x[Kebab-3]
	_ = x[Snake-4]
	_ = x[Space-5]
}

const _CaseType_name = "PascalCamelKebabSnakeSpace"

var _CaseType_index = [...]uint8{0, 6, 11, 16, 21, 26}

func (i CaseType) String() string {
	i -= 1
	if i < 0 || i >= CaseType(len(_CaseType_index)-1) {
		return "CaseType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CaseType_name[_CaseType_index[i]:_CaseType_index[i+1]]
}

func ParseCaseType(s string) CaseType {
	switch s {
	case "pascal":
		return Pascal
	case "camel":
		return Camel
	case "kebab":
		return Kebab
	case "snake":
		return Snake
	case "space":
		return Space
	default:
		return Pascal
	}
}
